receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}

processors:
  batch: {}
  spanmetrics:
    metrics_exporter: prometheus
    dimensions:
      - name: http.method
      - name: http.route
      - name: rpc.system
      - name: rpc.service
      - name: rpc.method

exporters:
  logging:
    loglevel: info
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, spanmetrics]
      exporters: [otlp/tempo, logging]
    metrics/spanmetrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
